'use client'

import { useEffect, useState } from 'react'
import { Brain, Loader2, Send } from 'lucide-react'

type Analytics = { has_data: boolean; orders_count: number; best_sellers: { name: string; quantity: number; revenue: string }[]; lowest_sellers: { name: string; quantity: number; revenue: string }[]; revenue_trend: { hour: string; revenue: string }[]; peak_hour: string | null; popular_category: string | null; average_order_value: string; pairs: string[] }

export default function AIInsights() {
  const [analytics, setAnalytics] = useState<Analytics | null>(null)
  const [question, setQuestion] = useState('')
  const [answer, setAnswer] = useState('')
  const [loading, setLoading] = useState(true)
  const [asking, setAsking] = useState(false)
  const [error, setError] = useState('')
  useEffect(() => { fetch('/api/dashboard/analytics', { headers: { Authorization: `Bearer ${sessionStorage.getItem('qrserve_token') ?? ''}` } }).then(async response => { if (!response.ok) throw new Error('Connect an owner session to view verified insights.') ; setAnalytics(await response.json()) }).catch(error => setError(error instanceof Error ? error.message : 'Analytics unavailable')).finally(() => setLoading(false)) }, [])
  const ask = async (event: React.FormEvent) => { event.preventDefault(); if (!question.trim() || !analytics) return; setAsking(true); setAnswer(''); try { const response = await fetch('/api/analytics/ask', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question, analytics }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail); setAnswer(data.answer) } catch (error) { setAnswer(error instanceof Error ? error.message : 'Unable to answer from current data.') } finally { setAsking(false) } }
  return <section className="mt-8 border border-border bg-card shadow-[0_16px_36px_-28px_hsl(var(--foreground))]"><div className="flex flex-col gap-4 border-b border-border p-5 md:flex-row md:items-center md:justify-between md:p-6"><div className="flex items-start gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-terracotta text-primary-foreground"><Brain className="size-4" /></span><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-terracotta">Verified intelligence</p><h3 className="mt-1 font-display text-xl font-bold tracking-tight">AI Insights</h3><p className="mt-1 text-sm text-muted-foreground">Answers grounded in completed orders from Neon.</p></div></div><span className="w-fit border border-sage/30 bg-sage/10 px-2.5 py-1.5 text-[10px] font-bold uppercase tracking-widest text-sage-foreground">Live data only</span></div>{loading ? <div className="mt-6 flex items-center gap-2 text-sm text-muted-foreground"><Loader2 className="size-4 animate-spin" />Loading live analytics…</div> : error ? <p className="mt-6 text-sm text-destructive">{error}</p> : !analytics?.has_data ? <div className="mt-6 rounded-xl border border-dashed border-border p-6 text-center text-sm text-muted-foreground">Complete orders will unlock seller, revenue, and recommendation insights.</div> : <><div className="grid border-b border-border sm:grid-cols-3"><Insight label="Best seller" value={analytics.best_sellers[0]?.name ?? 'No item data'} /><Insight label="Peak hour" value={analytics.peak_hour ?? 'Not enough data'} /><Insight label="Popular category" value={analytics.popular_category ?? 'Not categorized'} /></div><form onSubmit={ask} className="flex flex-col gap-2 p-5 md:flex-row md:p-6"><input value={question} onChange={event => setQuestion(event.target.value)} placeholder="Ask about your sales…" className="min-w-0 flex-1 rounded-xl border border-border bg-background px-4 py-3 text-sm" aria-label="Ask about your sales" /><button disabled={asking} className="inline-flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-bold text-primary-foreground disabled:opacity-60"><Send className="size-4" />Ask</button></form>{answer && <p className="mt-4 rounded-xl bg-secondary p-4 text-sm leading-6">{answer}</p>}</>}</section>
}
function Insight({ label, value }: { label: string; value: string }) { return <div className="border-r border-border p-5 last:border-r-0"><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-muted-foreground">{label}</p><p className="mt-3 truncate font-display text-lg font-bold">{value}</p></div> }
